/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;
import Login.Login;
import PharmacyJf.PharmacyJf;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.JFrame;


/**
 *
 * @author Ashfakur Rahman
 */
public class Doctor extends javax.swing.JFrame {
    private JFrame frame;

    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jtxtEmailAddress = new javax.swing.JTextField();
        jtxtPatientNHSNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtEMISNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jtxtGpAppointmentRef = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jtxtOfficePhoneNo1 = new javax.swing.JTextField();
        jtxtSureName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtOfficePhoneNo2 = new javax.swing.JTextField();
        jtxtMedicalCenterName = new javax.swing.JTextField();
        jtxtFaxNo = new javax.swing.JTextField();
        jtxtPatientId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtAddressOfCenter = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonPharmacy = new javax.swing.JButton();
        jButtonGpApp = new javax.swing.JButton();
        jButtonPatient = new javax.swing.JButton();
        jButtonPayment = new javax.swing.JButton();
        jButtonPharmacyOffice = new javax.swing.JButton();
        jButtonLogin2 = new javax.swing.JButton();
        jtxtPostCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtMedicalCenterRef = new javax.swing.JTextField();
        jcmbNameOfTablets = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Email Address:");

        jtxtEmailAddress.setBackground(new java.awt.Color(44, 62, 80));
        jtxtEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtEmailAddress.setForeground(new java.awt.Color(240, 240, 240));

        jtxtPatientNHSNo.setBackground(new java.awt.Color(44, 62, 80));
        jtxtPatientNHSNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtPatientNHSNo.setForeground(new java.awt.Color(240, 240, 240));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Patient NHS No:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("EMIS No:");

        jtxtEMISNo.setBackground(new java.awt.Color(44, 62, 80));
        jtxtEMISNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtEMISNo.setForeground(new java.awt.Color(240, 240, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Doctor's NHS No:");

        jtxtDoctorNHSNo.setBackground(new java.awt.Color(44, 62, 80));
        jtxtDoctorNHSNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtDoctorNHSNo.setForeground(new java.awt.Color(240, 240, 240));

        jtxtGpAppointmentRef.setBackground(new java.awt.Color(44, 62, 80));
        jtxtGpAppointmentRef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtGpAppointmentRef.setForeground(new java.awt.Color(240, 240, 240));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("GP Appointment Ref:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Doctor's Ref No:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Medical Center Ref:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("First Name:");

        jtxtFirstName.setBackground(new java.awt.Color(44, 62, 80));
        jtxtFirstName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtFirstName.setForeground(new java.awt.Color(240, 240, 240));

        jtxtOfficePhoneNo1.setBackground(new java.awt.Color(44, 62, 80));
        jtxtOfficePhoneNo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtOfficePhoneNo1.setForeground(new java.awt.Color(240, 240, 240));

        jtxtSureName.setBackground(new java.awt.Color(44, 62, 80));
        jtxtSureName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtSureName.setForeground(new java.awt.Color(240, 240, 240));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Office Phone No 1:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Sure Name:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Office Phone No 2:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Medical Center Name:");

        jtxtOfficePhoneNo2.setBackground(new java.awt.Color(44, 62, 80));
        jtxtOfficePhoneNo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtOfficePhoneNo2.setForeground(new java.awt.Color(240, 240, 240));

        jtxtMedicalCenterName.setBackground(new java.awt.Color(44, 62, 80));
        jtxtMedicalCenterName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtMedicalCenterName.setForeground(new java.awt.Color(240, 240, 240));

        jtxtFaxNo.setBackground(new java.awt.Color(44, 62, 80));
        jtxtFaxNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtFaxNo.setForeground(new java.awt.Color(240, 240, 240));

        jtxtPatientId.setBackground(new java.awt.Color(44, 62, 80));
        jtxtPatientId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtPatientId.setForeground(new java.awt.Color(240, 240, 240));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Patient ID:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Address of Center:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor's Ref No", "Doctor's NHS No", "First Name", "Sure Name", "Medical Center Name", "Patient ID", "Address of Center", "Post Code", "Medical Center Ref", "Office Phone No 1", "Office Phone No 2", "Fax No", "Email Address", "Patient NHS No", "EMIS No", "GP Appointment Ref"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jtxtAddressOfCenter.setBackground(new java.awt.Color(44, 62, 80));
        jtxtAddressOfCenter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtAddressOfCenter.setForeground(new java.awt.Color(240, 240, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(34, 167, 240));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 90, 30));

        jButtonUpdate.setBackground(new java.awt.Color(0, 255, 0));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 30));

        jButtonPharmacy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPharmacy.setText("Pharmacy");
        jButtonPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPharmacyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 30));

        jButtonGpApp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGpApp.setText("GP Appointment");
        jPanel1.add(jButtonGpApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 130, 30));

        jButtonPatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPatient.setText("Patient");
        jPanel1.add(jButtonPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 100, 30));

        jButtonPayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPayment.setText("Payment");
        jPanel1.add(jButtonPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 100, 30));

        jButtonPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPharmacyOffice.setText("Pharmacy Office");
        jPanel1.add(jButtonPharmacyOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 140, 30));

        jButtonLogin2.setBackground(new java.awt.Color(255, 0, 0));
        jButtonLogin2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLogin2.setText("Back");
        jButtonLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 90, 30));

        jtxtPostCode.setBackground(new java.awt.Color(44, 62, 80));
        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtPostCode.setForeground(new java.awt.Color(240, 240, 240));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Post Code:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Fax No:");

        jtxtMedicalCenterRef.setBackground(new java.awt.Color(44, 62, 80));
        jtxtMedicalCenterRef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtMedicalCenterRef.setForeground(new java.awt.Color(240, 240, 240));
        jtxtMedicalCenterRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMedicalCenterRefActionPerformed(evt);
            }
        });

        jcmbNameOfTablets.setBackground(new java.awt.Color(44, 62, 80));
        jcmbNameOfTablets.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcmbNameOfTablets.setForeground(new java.awt.Color(240, 240, 240));
        jcmbNameOfTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor's Ref", "JK123456", "SR123456", "NM123456", "NN123456" }));
        jcmbNameOfTablets.setToolTipText("");
        jcmbNameOfTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameOfTabletsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtAddressOfCenter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtPatientId)
                            .addComponent(jtxtMedicalCenterName)
                            .addComponent(jtxtSureName)
                            .addComponent(jtxtDoctorNHSNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtFirstName)
                            .addComponent(jtxtPostCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcmbNameOfTablets, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(jtxtEMISNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtPatientNHSNo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtMedicalCenterRef, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtOfficePhoneNo1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(76, 76, 76)
                                .addComponent(jtxtOfficePhoneNo2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151)
                                .addComponent(jtxtFaxNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jtxtEmailAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtGpAppointmentRef))))
                    .addComponent(jScrollPane1))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmbNameOfTablets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMedicalCenterRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtDoctorNHSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtOfficePhoneNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtOfficePhoneNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSureName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMedicalCenterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPatientNHSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAddressOfCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEMISNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtGpAppointmentRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin2ActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButtonLogin2ActionPerformed

    private void jButtonPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPharmacyActionPerformed
        PharmacyJf iPharmacyJf = new PharmacyJf();
        iPharmacyJf.setVisible(true);
    }//GEN-LAST:event_jButtonPharmacyActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{jcmbNameOfTablets.getSelectedItem().toString(),jtxtDoctorNHSNo.getText(),
            jtxtFirstName.getText(),jtxtSureName.getText(),jtxtMedicalCenterName.getText(),jtxtPatientId.getText(),
            jtxtAddressOfCenter.getText(),jtxtPostCode.getText(),jtxtMedicalCenterRef.getText(),
            jtxtOfficePhoneNo1.getText(),jtxtOfficePhoneNo2.getText(),jtxtFaxNo.getText(),
            jtxtEmailAddress.getText(),jtxtPatientNHSNo.getText(),jtxtEMISNo.getText(),
            jtxtGpAppointmentRef.getText(),});
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1)
        {
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null, "No data to delete","Pharmacy Management System",JOptionPane.OK_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Select a row to delete","Pharmacy Management System",JOptionPane.OK_OPTION);
            }
        }
        else
        {
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jtxtMedicalCenterRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMedicalCenterRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMedicalCenterRefActionPerformed

    private void jcmbNameOfTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameOfTabletsActionPerformed

        if(jcmbNameOfTablets.getSelectedItem().equals("JK123456"))
        {
            jtxtDoctorNHSNo.setText("DNHS0011");
            jtxtFirstName.setText("Jahangir");
            jtxtSureName.setText("Kabir");
            jtxtMedicalCenterName.setText("IBNSINA MEDICAL");
            jtxtPatientId.setText("P000011");
            jtxtAddressOfCenter.setText("Subhanighat,Sylhet");
            jtxtPostCode.setText("1531");
            jtxtMedicalCenterRef.setText("MCR001111");
            jtxtOfficePhoneNo1.setText("0252302150");
            jtxtOfficePhoneNo2.setText("0252403170");
            jtxtFaxNo.setText("0056987340");
            jtxtEmailAddress.setText("jk.medi@gmail.com");
            jtxtPatientNHSNo.setText("PNHS000011");
            jtxtEMISNo.setText("Y34567890");
            jtxtGpAppointmentRef.setText("Yes");
        }
        else if(jcmbNameOfTablets.getSelectedItem().equals("SR123456"))
        {
            jtxtDoctorNHSNo.setText("DNHS0012");
            jtxtFirstName.setText("Saklayen");
            jtxtSureName.setText("Rasel");
            jtxtMedicalCenterName.setText("IBNSINA MEDICAL");
            jtxtPatientId.setText("P000012");
            jtxtAddressOfCenter.setText("Subhanighat,Sylhet");
            jtxtPostCode.setText("1531");
            jtxtMedicalCenterRef.setText("MCR001112");
            jtxtOfficePhoneNo1.setText("0252302151");
            jtxtOfficePhoneNo2.setText("0252403171");
            jtxtFaxNo.setText("0056987341");
            jtxtEmailAddress.setText("sr.medi@gmail.com");
            jtxtPatientNHSNo.setText("PNHS000012");
            jtxtEMISNo.setText("Y34567891");
            jtxtGpAppointmentRef.setText("Yes");
        }

        else if(jcmbNameOfTablets.getSelectedItem().equals("NM123456"))
        {
            jtxtDoctorNHSNo.setText("DNHS0013");
            jtxtFirstName.setText("Nadim");
            jtxtSureName.setText("Mahmud");
            jtxtMedicalCenterName.setText("IBNSINA MEDICAL");
            jtxtPatientId.setText("P000013");
            jtxtAddressOfCenter.setText("Subhanighat,Sylhet");
            jtxtPostCode.setText("1531");
            jtxtMedicalCenterRef.setText("MCR001122");
            jtxtOfficePhoneNo1.setText("0252302152");
            jtxtOfficePhoneNo2.setText("0252403172");
            jtxtFaxNo.setText("0056987342");
            jtxtEmailAddress.setText("nm.medi@gmail.com");
            jtxtPatientNHSNo.setText("PNHS000013");
            jtxtEMISNo.setText("Y34567892");
            jtxtGpAppointmentRef.setText("Yes");
        }

        else if(jcmbNameOfTablets.getSelectedItem().equals("NN123456"))
        {
            jtxtDoctorNHSNo.setText("DNHS0014");
            jtxtFirstName.setText("Noshin");
            jtxtSureName.setText("Nawar");
            jtxtMedicalCenterName.setText("IBNSINA MEDICAL");
            jtxtPatientId.setText("P000014");
            jtxtAddressOfCenter.setText("Subhanighat,Sylhet");
            jtxtPostCode.setText("1531");
            jtxtMedicalCenterRef.setText("MCR001123");
            jtxtOfficePhoneNo1.setText("0252302153");
            jtxtOfficePhoneNo2.setText("0252403173");
            jtxtFaxNo.setText("0056987343");
            jtxtEmailAddress.setText("nn.medi@gmail.com");
            jtxtPatientNHSNo.setText("PNHS000014");
            jtxtEMISNo.setText("Y34567893");
            jtxtGpAppointmentRef.setText("Yes");
        }
    }//GEN-LAST:event_jcmbNameOfTabletsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonGpApp;
    private javax.swing.JButton jButtonLogin2;
    private javax.swing.JButton jButtonPatient;
    private javax.swing.JButton jButtonPayment;
    private javax.swing.JButton jButtonPharmacy;
    private javax.swing.JButton jButtonPharmacyOffice;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcmbNameOfTablets;
    private javax.swing.JTextField jtxtAddressOfCenter;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtEMISNo;
    private javax.swing.JTextField jtxtEmailAddress;
    private javax.swing.JTextField jtxtFaxNo;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtGpAppointmentRef;
    private javax.swing.JTextField jtxtMedicalCenterName;
    private javax.swing.JTextField jtxtMedicalCenterRef;
    private javax.swing.JTextField jtxtOfficePhoneNo1;
    private javax.swing.JTextField jtxtOfficePhoneNo2;
    private javax.swing.JTextField jtxtPatientId;
    private javax.swing.JTextField jtxtPatientNHSNo;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextField jtxtSureName;
    // End of variables declaration//GEN-END:variables
}
