/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PharmacyJf;

import Doctor.Doctor;
import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashfakur Rahman
 */
public class PharmacyJf extends javax.swing.JFrame {

    /**
     * Creates new form PharmacyJf
     */
    public PharmacyJf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtRef = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jtxtNumOfTab = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtLot = new javax.swing.JTextField();
        jtxtIssueDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtDrivingAndUsingMachine = new javax.swing.JTextField();
        jtxtHowToUseMedication = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtPossibleSideEffect = new javax.swing.JTextField();
        jtxtFurtherInfo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtStrogaeAdvice = new javax.swing.JTextField();
        jtxtAdministration = new javax.swing.JTextField();
        jcmbNameOfTablets = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDoctor = new javax.swing.JButton();
        jButtonGpApp = new javax.swing.JButton();
        jButtonPatient = new javax.swing.JButton();
        jButtonPayment = new javax.swing.JButton();
        jButtonPharmacyOffice = new javax.swing.JButton();
        jButtonLogin2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reference No.");

        jtxtRef.setBackground(new java.awt.Color(44, 62, 80));
        jtxtRef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtRef.setForeground(new java.awt.Color(240, 240, 240));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Name of Tablets: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Dose(mg):");

        jtxtDose.setBackground(new java.awt.Color(44, 62, 80));
        jtxtDose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtDose.setForeground(new java.awt.Color(240, 240, 240));

        jtxtNumOfTab.setBackground(new java.awt.Color(44, 62, 80));
        jtxtNumOfTab.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtNumOfTab.setForeground(new java.awt.Color(240, 240, 240));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Number of Tablets:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("LOT:");

        jtxtLot.setBackground(new java.awt.Color(44, 62, 80));
        jtxtLot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtLot.setForeground(new java.awt.Color(240, 240, 240));

        jtxtIssueDate.setBackground(new java.awt.Color(44, 62, 80));
        jtxtIssueDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtIssueDate.setForeground(new java.awt.Color(240, 240, 240));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Issued Date:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Exp Date:");

        jtxtExpDate.setBackground(new java.awt.Color(44, 62, 80));
        jtxtExpDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtExpDate.setForeground(new java.awt.Color(240, 240, 240));

        jtxtDailyDose.setBackground(new java.awt.Color(44, 62, 80));
        jtxtDailyDose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtDailyDose.setForeground(new java.awt.Color(240, 240, 240));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Daily Dose:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Administration:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Driving and Using Machines:");

        jtxtDrivingAndUsingMachine.setBackground(new java.awt.Color(44, 62, 80));
        jtxtDrivingAndUsingMachine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtDrivingAndUsingMachine.setForeground(new java.awt.Color(240, 240, 240));

        jtxtHowToUseMedication.setBackground(new java.awt.Color(44, 62, 80));
        jtxtHowToUseMedication.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtHowToUseMedication.setForeground(new java.awt.Color(240, 240, 240));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("How to Use Medication:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Patient ID:");

        jtxtPatientID.setBackground(new java.awt.Color(44, 62, 80));
        jtxtPatientID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtPatientID.setForeground(new java.awt.Color(240, 240, 240));

        jtxtDoctorNHSNo.setBackground(new java.awt.Color(44, 62, 80));
        jtxtDoctorNHSNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtDoctorNHSNo.setForeground(new java.awt.Color(240, 240, 240));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Doctors NHS No:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Possible Side Effect:");

        jtxtPossibleSideEffect.setBackground(new java.awt.Color(44, 62, 80));
        jtxtPossibleSideEffect.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtPossibleSideEffect.setForeground(new java.awt.Color(240, 240, 240));

        jtxtFurtherInfo.setBackground(new java.awt.Color(44, 62, 80));
        jtxtFurtherInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtFurtherInfo.setForeground(new java.awt.Color(240, 240, 240));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Further Information:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Storage Advice:");

        jtxtStrogaeAdvice.setBackground(new java.awt.Color(44, 62, 80));
        jtxtStrogaeAdvice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtStrogaeAdvice.setForeground(new java.awt.Color(240, 240, 240));

        jtxtAdministration.setBackground(new java.awt.Color(44, 62, 80));
        jtxtAdministration.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtAdministration.setForeground(new java.awt.Color(240, 240, 240));

        jcmbNameOfTablets.setBackground(new java.awt.Color(44, 62, 80));
        jcmbNameOfTablets.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcmbNameOfTablets.setForeground(new java.awt.Color(240, 240, 240));
        jcmbNameOfTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a Selection", "Ibuprofen", "Paracetamol", "Napa Extra", "Fexo 120" }));
        jcmbNameOfTablets.setSelectedItem(jcmbNameOfTablets.getSelectedItem());
        jcmbNameOfTablets.setToolTipText("");
        jcmbNameOfTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameOfTabletsActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No", "Dose(mg)", "Number of Tablets", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Possible Side Effect", "Further Information", "Storage Advice", "Administration", "Driving and Using Machines", "How to Use Medication", "Patient ID", "Doctor NHS No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(34, 167, 240));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 90, 30));

        jButtonUpdate.setBackground(new java.awt.Color(0, 255, 0));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 30));

        jButtonDoctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDoctor.setText("Doctor");
        jButtonDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, 30));

        jButtonGpApp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonGpApp.setText("GP Appointment");
        jPanel1.add(jButtonGpApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 130, 30));

        jButtonPatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPatient.setText("Patient");
        jPanel1.add(jButtonPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, 30));

        jButtonPayment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPayment.setText("Payment");
        jPanel1.add(jButtonPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 100, 30));

        jButtonPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonPharmacyOffice.setText("Pharmacy Office");
        jPanel1.add(jButtonPharmacyOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 140, 30));

        jButtonLogin2.setBackground(new java.awt.Color(255, 0, 0));
        jButtonLogin2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLogin2.setText("Back");
        jButtonLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogin2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(38, 38, 38))
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtExpDate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtIssueDate)
                            .addComponent(jtxtLot)
                            .addComponent(jtxtNumOfTab)
                            .addComponent(jcmbNameOfTablets, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtRef, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtDose)
                            .addComponent(jtxtDailyDose, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel15))
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(77, 77, 77)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(119, 119, 119)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPossibleSideEffect, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jtxtHowToUseMedication, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtPatientID)
                            .addComponent(jtxtDrivingAndUsingMachine)
                            .addComponent(jtxtAdministration)
                            .addComponent(jtxtStrogaeAdvice)
                            .addComponent(jtxtFurtherInfo)
                            .addComponent(jtxtDoctorNHSNo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPossibleSideEffect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbNameOfTablets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFurtherInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtStrogaeAdvice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAdministration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNumOfTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDrivingAndUsingMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtHowToUseMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDoctorNHSNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDailyDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbNameOfTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameOfTabletsActionPerformed
        // TODO add your handling code here:
        if(jcmbNameOfTablets.getSelectedItem().equals("Ibuprofen"))//Paracetamol, Napa Extra, Fexo 120, Ibuprofen, Co-codamol, Amlodipine
        {
            jtxtRef.setText("Ibu005875");
            jtxtDose.setText("200");
            jtxtNumOfTab.setText("12");
            jtxtLot.setText("56005875");
            jtxtIssueDate.setText("03/06/2021");
            jtxtExpDate.setText("03/06/2022");
            jtxtDailyDose.setText("3");
            
            jtxtPossibleSideEffect.setText("Bleeding");
            jtxtFurtherInfo.setText("Place Dispensary");
            jtxtStrogaeAdvice.setText("Less than 20%");
            jtxtAdministration.setText("Yes Actioned");
            jtxtDrivingAndUsingMachine.setText("No");
            jtxtHowToUseMedication.setText("Use Water, No Alcohol");
            jtxtPatientID.setText("P00000001");
            jtxtDoctorNHSNo.setText("NHS5678");
        }
        else if(jcmbNameOfTablets.getSelectedItem().equals("Paracetamol"))//Paracetamol, Napa Extra, Fexo 120, Ibuprofen, Co-codamol, Amlodipine
        {
            jtxtRef.setText("Para005876");
            jtxtDose.setText("500");
            jtxtNumOfTab.setText("24");
            jtxtLot.setText("98543669");
            jtxtIssueDate.setText("04/06/2021");
            jtxtExpDate.setText("04/06/2023");
            jtxtDailyDose.setText("2");
            
            jtxtPossibleSideEffect.setText("Feeling Sick");
            jtxtFurtherInfo.setText("Place Dispensary");
            jtxtStrogaeAdvice.setText("Less than 25%");
            jtxtAdministration.setText("Yes Actioned");
            jtxtDrivingAndUsingMachine.setText("No");
            jtxtHowToUseMedication.setText("Use Water, No Alcohol");
            jtxtPatientID.setText("P00000002");
            jtxtDoctorNHSNo.setText("NHS7784");
        }
        else if(jcmbNameOfTablets.getSelectedItem().equals("Napa Extra"))//Paracetamol, Napa Extra, Fexo 120, Ibuprofen, Co-codamol, Amlodipine
        {
            jtxtRef.setText("Napa005878");
            jtxtDose.setText("500");
            jtxtNumOfTab.setText("36");
            jtxtLot.setText("09876543");
            jtxtIssueDate.setText("05/06/2021");
            jtxtExpDate.setText("05/06/2024");
            jtxtDailyDose.setText("3");
            
            jtxtPossibleSideEffect.setText("nausea");
            jtxtFurtherInfo.setText("Place Dispensary");
            jtxtStrogaeAdvice.setText("Less than 20%");
            jtxtAdministration.setText("Yes Actioned");
            jtxtDrivingAndUsingMachine.setText("No");
            jtxtHowToUseMedication.setText("Use Water, No Alcohol");
            jtxtPatientID.setText("P00000003");
            jtxtDoctorNHSNo.setText("NHS2345");
        }
        else if(jcmbNameOfTablets.getSelectedItem().equals("Fexo 120"))//Paracetamol, Napa Extra, Fexo 120, Ibuprofen, Co-codamol, Amlodipine
        {
            jtxtRef.setText("Fexo005879");
            jtxtDose.setText("120");
            jtxtNumOfTab.setText("48");
            jtxtLot.setText("12345678");
            jtxtIssueDate.setText("02/06/2021");
            jtxtExpDate.setText("02/06/2025");
            jtxtDailyDose.setText("1");
            
            jtxtPossibleSideEffect.setText("stomach upset");
            jtxtFurtherInfo.setText("Place Dispensary");
            jtxtStrogaeAdvice.setText("Less than 23%");
            jtxtAdministration.setText("Yes Actioned");
            jtxtDrivingAndUsingMachine.setText("No");
            jtxtHowToUseMedication.setText("Use Water, No Alcohol");
            jtxtPatientID.setText("P00000004");
            jtxtDoctorNHSNo.setText("NHS0987");
        }
        
        
    }//GEN-LAST:event_jcmbNameOfTabletsActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1)
        {
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null, "No data to delete","Pharmacy Management System",JOptionPane.OK_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Select a row to delete","Pharmacy Management System",JOptionPane.OK_OPTION);
            }
        }
        else
        {
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    
    private void jButtonLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogin2ActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButtonLogin2ActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.addRow(new Object[]{jcmbNameOfTablets.getSelectedItem().toString(),jtxtRef.getText(),
        jtxtDose.getText(),jtxtNumOfTab.getText(),jtxtLot.getText(),jtxtIssueDate.getText(),
        jtxtExpDate.getText(),jtxtDailyDose.getText(),jtxtPossibleSideEffect.getText(),
        jtxtFurtherInfo.getText(),jtxtStrogaeAdvice.getText(),jtxtAdministration.getText(),
        jtxtDrivingAndUsingMachine.getText(),jtxtHowToUseMedication.getText(),jtxtPatientID.getText(),
        jtxtDoctorNHSNo.getText(),});
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoctorActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jButtonDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyJf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyJf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyJf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyJf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyJf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonDoctor;
    private javax.swing.JButton jButtonGpApp;
    private javax.swing.JButton jButtonLogin2;
    private javax.swing.JButton jButtonPatient;
    private javax.swing.JButton jButtonPayment;
    private javax.swing.JButton jButtonPharmacyOffice;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcmbNameOfTablets;
    private javax.swing.JTextField jtxtAdministration;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingAndUsingMachine;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInfo;
    private javax.swing.JTextField jtxtHowToUseMedication;
    private javax.swing.JTextField jtxtIssueDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumOfTab;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPossibleSideEffect;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStrogaeAdvice;
    // End of variables declaration//GEN-END:variables

    public void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
