/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Doctor.Doctor;
import PharmacyJf.PharmacyJf;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pharmacy.Pharmacy;

/**
 *
 * @author Ashfakur Rahman
 */
public class Login extends javax.swing.JFrame {
    
    int attempt = 0;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jButtonExit = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonPatient = new javax.swing.JButton();
        jButtonDoctor = new javax.swing.JButton();
        jButtonPharmacy = new javax.swing.JButton();
        jButtonPharmacyOffice = new javax.swing.JButton();
        jButtonPayment = new javax.swing.JButton();
        jButtonAppointment = new javax.swing.JButton();
        jButtonSpecialist = new javax.swing.JButton();
        jButtonSurgery = new javax.swing.JButton();
        jButtonHospital = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jButtonConsultant = new javax.swing.JButton();
        jButtonPharmacist = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(1, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 41));

        jtxtUsername.setBackground(new java.awt.Color(240, 240, 240));
        jtxtUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 105, 270, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 41));

        jPassword.setBackground(new java.awt.Color(240, 240, 240));
        jPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 270, 40));

        jButtonExit.setBackground(new java.awt.Color(255, 0, 0));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 140, 40));

        jButtonLogin.setBackground(new java.awt.Color(0, 255, 0));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 40));

        jButtonCancel.setBackground(new java.awt.Color(34, 167, 240));
        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("  Register Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 10, 320, -1));

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 70));

        jButtonPatient.setBackground(new java.awt.Color(248, 148, 6));
        jButtonPatient.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonPatient.setText("Patient");
        jButtonPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPatientActionPerformed(evt);
            }
        });

        jButtonDoctor.setBackground(new java.awt.Color(248, 148, 6));
        jButtonDoctor.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonDoctor.setText("Doctor");
        jButtonDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoctorActionPerformed(evt);
            }
        });

        jButtonPharmacy.setBackground(new java.awt.Color(248, 148, 6));
        jButtonPharmacy.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonPharmacy.setText("Pharmacy");
        jButtonPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPharmacyActionPerformed(evt);
            }
        });

        jButtonPharmacyOffice.setBackground(new java.awt.Color(248, 148, 6));
        jButtonPharmacyOffice.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonPharmacyOffice.setText("Pharmacy Office");
        jButtonPharmacyOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPharmacyOfficeActionPerformed(evt);
            }
        });

        jButtonPayment.setBackground(new java.awt.Color(248, 148, 6));
        jButtonPayment.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonPayment.setText("Payment");
        jButtonPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaymentActionPerformed(evt);
            }
        });

        jButtonAppointment.setBackground(new java.awt.Color(248, 148, 6));
        jButtonAppointment.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonAppointment.setText("GPAppointment");
        jButtonAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppointmentActionPerformed(evt);
            }
        });

        jButtonSpecialist.setBackground(new java.awt.Color(248, 148, 6));
        jButtonSpecialist.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonSpecialist.setText("Specialist");

        jButtonSurgery.setBackground(new java.awt.Color(248, 148, 6));
        jButtonSurgery.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonSurgery.setText("Surgery");

        jButtonHospital.setBackground(new java.awt.Color(248, 148, 6));
        jButtonHospital.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonHospital.setText("Hospital");

        jButtonHelp.setBackground(new java.awt.Color(248, 148, 6));
        jButtonHelp.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonHelp.setText("Help");

        jButtonConsultant.setBackground(new java.awt.Color(248, 148, 6));
        jButtonConsultant.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonConsultant.setText("Consultant");

        jButtonPharmacist.setBackground(new java.awt.Color(248, 148, 6));
        jButtonPharmacist.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonPharmacist.setText("Pharmacist");
        jButtonPharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPharmacistActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("  Pharmacy Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPharmacyOffice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHelp))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPharmacy)
                            .addComponent(jButtonPatient)
                            .addComponent(jButtonPayment)
                            .addComponent(jButtonAppointment)
                            .addComponent(jButtonDoctor))
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 113, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonConsultant)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSurgery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSpecialist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonPharmacist))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDoctor)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPharmacy)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPatient)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPayment)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAppointment)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPharmacyOffice))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSurgery)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHospital)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSpecialist)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConsultant)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPharmacist)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHelp))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to Exit","Pharmacy Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        jtxtUsername.setText("");
        jPassword.setText("");
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoctorActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jButtonDoctorActionPerformed

    private void jButtonPharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPharmacistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPharmacistActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        jButtonDoctor.setEnabled(false);
        jButtonPharmacy.setEnabled(false);
        jButtonPatient.setEnabled(false);
        jButtonPayment.setEnabled(false);
        jButtonAppointment.setEnabled(false);
        jButtonPharmacyOffice.setEnabled(false);
        jButtonSurgery.setEnabled(false);
        jButtonHospital.setEnabled(false);
        jButtonSpecialist.setEnabled(false);
        jButtonConsultant.setEnabled(false);
        jButtonPharmacist.setEnabled(false);
        jButtonHelp.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        
        String Username = jtxtUsername.getText();
        String Password = jPassword.getText();
        
        if(Username.contains("Ashfakur Rahman")&& (Password.contains("2018331524")))
        {
            jtxtUsername.setText("");
            jPassword.setText("");
            
            jButtonDoctor.setEnabled(true);
            jButtonPharmacy.setEnabled(true);
            jButtonPatient.setEnabled(true);
            jButtonPayment.setEnabled(true);
            jButtonAppointment.setEnabled(true);
            jButtonPharmacyOffice.setEnabled(true);
            jButtonSurgery.setEnabled(true);
            jButtonHospital.setEnabled(true);
            jButtonSpecialist.setEnabled(true);
            jButtonConsultant.setEnabled(true);
            jButtonPharmacist.setEnabled(true);
            jButtonHelp.setEnabled(true);
        }
        else if(!(Username.contains("one")&& (Password.contains("one"))))
                {
                    jtxtUsername.setText("");
                    jPassword.setText("");
                    
                    jButtonDoctor.setEnabled(false);
                    jButtonPharmacy.setEnabled(false);
                    jButtonPatient.setEnabled(false);
                    jButtonPayment.setEnabled(false);
                    jButtonAppointment.setEnabled(false);
                    jButtonPharmacyOffice.setEnabled(false);
                    jButtonSurgery.setEnabled(false);
                    jButtonHospital.setEnabled(false);
                    jButtonSpecialist.setEnabled(false);
                    jButtonConsultant.setEnabled(false);
                    jButtonPharmacist.setEnabled(false);
                    jButtonHelp.setEnabled(false);
                    attempt += 1;
                    if(attempt==3)
                    {
                        System.exit(0);
                    }
                }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPharmacyActionPerformed
        PharmacyJf myPharmacy = new PharmacyJf();
        myPharmacy.setVisible(true);
        
    }//GEN-LAST:event_jButtonPharmacyActionPerformed

    private void jButtonPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPatientActionPerformed
        PharmacyJf iPharmacyJf = new PharmacyJf();
        iPharmacyJf.setVisible(true);
    }//GEN-LAST:event_jButtonPatientActionPerformed

    private void jButtonAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppointmentActionPerformed
        PharmacyJf iPharmacyJf = new PharmacyJf();
        iPharmacyJf.setVisible(true);
    }//GEN-LAST:event_jButtonAppointmentActionPerformed

    private void jButtonPharmacyOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPharmacyOfficeActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jButtonPharmacyOfficeActionPerformed

    private void jButtonPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaymentActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jButtonPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAppointment;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConsultant;
    private javax.swing.JButton jButtonDoctor;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonHospital;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonPatient;
    private javax.swing.JButton jButtonPayment;
    private javax.swing.JButton jButtonPharmacist;
    private javax.swing.JButton jButtonPharmacy;
    private javax.swing.JButton jButtonPharmacyOffice;
    private javax.swing.JButton jButtonSpecialist;
    private javax.swing.JButton jButtonSurgery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
